server:
  port: 8080
  error:
    include-message: always
spring:
  jackson:
    default-property-inclusion: non_null
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /ClearingHouseAPI.yml

## Auto setup protected with Keyclock
keycloak:
  auth-server-url: https://centralidp.int.demo.catena-x.net/auth
  #realm: CX-Central
  #resource: Cl2-CX-Portal
  use-resource-role-mappings: true
  bearer-only: true

portal:
  #url: https://portal-backend.int.demo.catena-x.net
  #auth-server-url: https://centralidp.int.demo.catena-x.net/auth
  #realm: CX-Central
  #clientId: sa-cl2-02
  #clientSecret: c7uhxqYONsR1SG5QO2lhh06Wzn1whifH

compliance-json:
  file-path: classpath:compliance.json
