apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dummy-service.applicationSecret.name" . }}
type: Opaque
stringData:  
  auth-server-url: {{ .Values.dummy-service.secret.authServerUrl | default "https://auth" }}
  realm: {{ .Values.dummyservice.secret.realm | default (printf "%s-%s" "realm" (randAlpha 6)) }}
  resource: {{ .Values.dummyservice.secret.resource | default (printf "%s-%s" "resource" (randAlpha 5)) }}
  ClientID: {{ .Values.dummyservice.secret.clientId | default (randAlphaNum 16) }}
  ClientSecret: {{ .Values.dummyservice.secret.clientSecret | default (randAlphaNum 16) }}
  portalurl: {{ .Values.dummyservice.secret.portalurl | default "https://portalurl" }}
  