apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dummy-service.applicationSecret.name" . }}
type: Opaque
stringData:  
  ClientID: {{ .Values.dummyservice.secret.clientId | default (randAlphaNum 16) }}
  ClientSecret: {{ .Values.dummyservice.secret.clientSecret | default (randAlphaNum 16) }}
  
