apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dummy-service.applicationSecret.name" . }}
type: Opaque
stringData:
  ClientSecret: {{ .Values.dummyservice.secret.clientSecret | default (randAlphaNum 16) }}
