ingress:
  enabled: true
  className: "nginx"
  issuer: "letsencrypt-prod"
  domain: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx

    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: clearing-house-stable.dev.demo.catena-x.net
      paths:
        - path: /
          pathType: Prefix


  tls:
    - tlsName: clearing-house-stable.dev.demo.catena-x.net-tls
      hosts:
        - clearing-house-stable.dev.demo.catena-x.net

 
dummyservice:
  secret:
    clientSecret: "<path:essential-services/data/dummy-service-stable#clientSecret>"
    portalurl: "<path:essential-services/data/dummy-service-stable#portal-url>"
    clientId: "<path:essential-services/data/dummy-service-stable#clientId>"
    authServerUrl: "<path:essential-services/data/dummy-service-stable#auth-server-url>"
    realm: "<path:essential-services/data/dummy-service-stable#realm>"
    resource: "<path:essential-services/data/dummy-service-stable#resource>"
    
# -- Pod resources requests and limits configuration
resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 300Mi
