ingress:
  enabled: true
  className: "nginx"
  issuer: "letsencrypt-prod"
  domain: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx

    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: clearing-house-beta.dev.demo.catena-x.net
      paths:
        - path: /
          pathType: Prefix


  tls:
    - tlsName: clearing-house-beta.dev.demo.catena-x.net-tls
      hosts:
        - clearing-house-beta.dev.demo.catena-x.net

      
# -- Pod resources requests and limits configuration
resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 300Mi
