ingress:
  enabled: true
  className: "nginx"
  issuer: "letsencrypt-prod"
  domain: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx

    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: dummy.dev.demo.catena-x.net
      paths:
        - path: /
          pathType: Prefix


  tls:
    - tlsName: dummy.dev.demo.catena-x.net-tls
      hosts:
        - dummy.dev.demo.catena-x.net

      
# -- Pod resources requests and limits configuration
resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 300Mi


dummy-service:
  secret:
    portalurl: "<path:essential-services/data/dummy-service#portal-url>"
    clientId: "<path:essential-services/data/dummy-service#clientId>"
    clientSecret: "<path:essential-services/data/dummy-service#clientSecret>"
    authServerUrl: "<path:essential-services/data/dummy-service#auth-server-url>"
    realm: "<path:essential-services/data/dummy-service#realm>"
    resource: "<path:essential-services/data/dummy-service#resource>"
