
name: Dummy Service
on:
  push:
    branches:
      - main
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

env:
  # Use GH Container Registry instead of docker
  # github.repository equals to <account|org>/<repo>
  REGISTRY: ghcr.io
  IMAGE_NAME: adkumar1/dummy-clearing-house/dummy-service

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Create SemVer or ref tags dependent of trigger event
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}},value=0.1.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
         REGISTRY: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUBTOKEN }}
         
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

